on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: wtfjoke/setup-tectonic@v4

      - name: Compile
        run: tectonic main.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: main.pdf

      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: release-${{ env.SHORT_SHA }}
          name: "Release: ${{ env.SHORT_SHA }}"
          files: main.pdf
