on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: wtfjoke/setup-tectonic@v4

      - name: Compile
        run: tectonic main.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: main.pdf

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: main.pdf
